### ISSUE TITLE
Design tutorial

### ISSUE THREAD

**Issue by GroDoggo** [AmelieEve/UnitySummerGameJam#6]
What could be a good tutorial? How the map should look like? What could be the forbidden action?

**Comment by AnthonyLeGourrierec** [comment]
Following your discord sketch, isn't opening the door the forbidden action? So if after that you teleport, maybe another version of the room, without the cristal and without the door, then you'll be able de change time again to go back to the previous scene, but this time you are on the other side, being able to reach the cristal?

**Comment by GroDoggo** [comment]
> Following your discord sketch, isn't opening the door the forbidden action? So if after that you teleport, maybe another version of the room, without the cristal and without the door, then you'll be able de change time again to go back to the previous scene, but this time you are on the other side, being able to reach the cristal?

I've written a full description of this tutorial

## Context:
The player begins their adventure in a small room located at the southern end of the level. This room is bathed in a mysterious violet hue, projecting glimpses of historical events. These visions give the player the impression that they are traveling through time.

## Initial Objective:
Upon leaving the small room, the player immediately spots the glowing, floating Chronolith through a transparent window. This clear, direct view signals to the player that their main objective is to reach the Chronolith.

## Tutorial Mechanics:
### Observation and Understanding:

The player has a clear view of the Chronolith as soon as they leave the starting room, providing strong visual motivation.
### First Attempt and Consequence:

The player's first instinct might be to open the door to reach the Chronolith. However, this action triggers a time dilation effect, teleporting the player back to the start. This teaches the player that certain actions can disrupt time and have unwanted consequences.
### Solution to Reach the Chronolith:

The player must explore the environment to find a stone, which is easily accessible.
They have two options to progress:
- **Break the Window**: Throwing the stone at the window will shatter it, allowing direct access to the Chronolith.
- **Break the Door**: Alternatively, the player can throw the stone at the door to break it down, providing another path to the Chronolith.
### Activation and Transition:

- Once the player approaches the Chronolith, it activates, stabilizing time and marking the end of the tutorial.
- The player is then teleported to the first real level of the game, ready to continue their adventure with an understanding of the basic game mechanics.
## Key Points for Collaborators:
- **Clear Visual Cues**: Ensure the Chronolith is clearly visible through the window from the start.
- **Visual and Auditory Feedback**: Use visual and sound effects to signal time dilation and teleportation.
- **Object Accessibility**: Make the stone easy to find to avoid player frustration.
- **Multiple Solutions**: Providing multiple solutions (breaking the window or the door) encourages creativity and exploration.
