### ISSUE TITLE
Create a script to detect forbidden actions

### ISSUE THREAD

**Issue by GroDoggo** [AmelieEve/UnitySummerGameJam#7]
Create an abstract (is it possible in C# ?) that allow the following things : 

- [ ] Children class should have a detectForbidenAction() that return a boolean
- [ ] Check in update if detectForbidenAction() is true
- [ ] Teleport to another level if yes

**Comment by AnthonyLeGourrierec** [comment]
To see with Amelie but maybe it is easier to use a "scriptable object" or something like that, I'm not familiar with abstraction in c#.

**Comment by GroDoggo** [comment]
Proposition using scriptable objects

- Create a new scritable object class like `ForbiddenAction` with the following properties : 
  - name
  - description
  - isTriggered
- Create instances of `ForbiddenAction`
- Create a `ForbiddenActionManager` script
  - Check every update if assigned `ForbiddenAction` is triggered
  - If yes, teleport player
- Create multiple scripts for each scene that can trigger the `ForbiddenAction`
  - Example : A script for the door. If player click to open it, `ForbiddenAction` is trigger
